<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "個") %> のエラーがあります:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <h5>お名前・ニックネーム</h5>
    <%= form.text_field :name, id: :user_name, placeholder: "お名前・ニックネーム", :size=>"50" %>
  </div>

  <div class="field">
    <h5>メールアドレス</h5>
    <%= form.text_field :email, id: :user_email, placeholder: "メールアドレス　ログイン名になります", :size=>"50" %>
  </div>

  <div class="field">
    <h5>パスワード</h5>
    <%= form.password_field :password, id: :user_password, placeholder: "パスワード", :size=>"50" %>
  </div>

  <div class="field">
    <h5>パスワード(確認)</h5>
    <%= form.password_field :password, id: :user_password_confirmation, placeholder: "確認のためもう一度パスワードを入力してください", :size=>"50" %>
  </div>

  <div class="actions">
    <%= form.submit "上記で登録します", class: 'btn btn-warning' %>
  </div>
<% end %>
